[package]
name = "simualtion"
version = "0.1.0"
authors = ["Denis K. <orca84@protonmail.com>"]
edition = "2018"

[dependencies]
# diesel = { version = "1.4.5", features = ["sqlite"] }
rppal = "0.11.3"
rs_ws281x = "0.3.1"
rand = "0.7.3"
